config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'reviews/new'

  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end

  resources :reviews, only: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORY = %w(chinese italian japanese french belgian)
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: CATEGORY }
end

app/models/review.rb
class Review < ApplicationRecord
  RATING = [0, 1, 2, 3, 4, 5]
  belongs_to :restaurant
  validates :rating, presence: true
  validates :rating, numericality: { only_integer: true }, inclusion: { in: 0..5}
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant), notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.'
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant

    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @restaurant = @review.restaurant
    @review.destroy

    redirect_to restaurant_path(@restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-4">
      <%= simple_form_for(@restaurant) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <div class="form-inputs">
          <%= f.input :name %>
          <%= f.input :address %>
          <%= f.input :category, collection: Restaurant::CATEGORY%>
          <%= f.input :phone_number %>
        </div>

        <div class="form-actions">
          <%= f.button :submit, 'Submit', class: 'btn btn-info' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/restaurants/edit.html.erb
<%= render 'form' %>

app/views/restaurants/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1 class="text-center">Restaurants</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Address</th>
        <th>Phone</th>
        <th>Category</th>
        <th>Action</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @restaurants.each do |restaurant| %>
        <tr>
          <td><%= restaurant.name %></td>
          <td><%= restaurant.address %></td>
          <td><%= restaurant.phone_number %></td>
          <td><%= restaurant.category %></td>
          <td><%= link_to 'Show', restaurant, class: 'btn btn-info' %></td>
          <td><%= link_to 'Edit', edit_restaurant_path(restaurant), class: 'btn btn-info' %></td>
          <td><%= link_to 'Delete', restaurant, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to 'New Restaurant', new_restaurant_path, class: 'btn btn-primary center' %>
</div>

app/views/restaurants/new.html.erb
<%= render 'form' %>

app/views/restaurants/show.html.erb
<div class="container p-3 my-3 bg-dark text-white">
  <p id="notice"><%= notice %></p>
  <h3>Welcome to <%= @restaurant.name %> </h3>

  <p>
    <strong>Address:</strong>
    <%= @restaurant.address %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= @restaurant.phone_number %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= @restaurant.category %>
  </p>

  <p>
    <ul>
      <% @restaurant.reviews.each do |review| %>
        <li><%= review.content %>
        <%= review.rating %>
        <%= link_to 'remove', review_path(review), method: :delete, data: { confirm: 'Are you sure?' } %></li>
     <% end %>
    </ul>
  </p>

  <%= link_to 'Edit', edit_restaurant_path(@restaurant), class: 'btn btn-info' %>
  <%= link_to 'Back', restaurants_path, class: 'btn btn-info' %>
  <%= link_to 'Add Review', new_restaurant_review_path(@restaurant), class: 'btn btn-info' %>
</div>

app/views/reviews/new.html.erb
<div class="container col-4 shadow p-3 mb-5 bg-white rounded">
  <h4 class="text-center mt-5">New Review for Restaurant</h4>
  <p class="text-center"><%= @restaurant.name %></p>


  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating, collection: Review::RATING %>
    <%= f.submit %>
  <% end %>
</div>